package wsCalculadora;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.1
 * 2023-12-10T14:47:11.988+01:00
 * Generated source version: 3.6.1
 *
 */
@WebService(targetNamespace = "http://calculadora/", name = "OperacionesCalculadora")
@XmlSeeAlso({ObjectFactory.class})
public interface OperacionesCalculadora {

    @WebMethod(action = "urn:ImplementarRestar")
    @RequestWrapper(localName = "implementarRestar", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementarRestar")
    @ResponseWrapper(localName = "implementarRestarResponse", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementarRestarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double implementarRestar(

        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );

    @WebMethod(action = "urn:ImplementarMultiplicar")
    @RequestWrapper(localName = "implementarMultiplicar", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementarMultiplicar")
    @ResponseWrapper(localName = "implementarMultiplicarResponse", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementarMultiplicarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double implementarMultiplicar(

        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );

    @WebMethod(action = "urn:Operar")
    @RequestWrapper(localName = "operar", targetNamespace = "http://calculadora/", className = "wsCalculadora.Operar")
    @ResponseWrapper(localName = "operarResponse", targetNamespace = "http://calculadora/", className = "wsCalculadora.OperarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double operar(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    ) throws Exception_Exception;

    @WebMethod(action = "urn:GetOperaciones")
    @RequestWrapper(localName = "getOperaciones", targetNamespace = "http://calculadora/", className = "wsCalculadora.GetOperaciones")
    @ResponseWrapper(localName = "getOperacionesResponse", targetNamespace = "http://calculadora/", className = "wsCalculadora.GetOperacionesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getOperaciones(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod(action = "urn:ImplementarDividir")
    @RequestWrapper(localName = "implementarDividir", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementarDividir")
    @ResponseWrapper(localName = "implementarDividirResponse", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementarDividirResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double implementarDividir(

        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    ) throws Exception_Exception;

    @WebMethod(action = "urn:ImplementacionMA")
    @RequestWrapper(localName = "implementacionMA", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementacionMA")
    @ResponseWrapper(localName = "implementacionMAResponse", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementacionMAResponse")
    public void implementacionMA()
;

    @WebMethod(action = "urn:ImplementacionMO")
    @RequestWrapper(localName = "implementacionMO", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementacionMO")
    @ResponseWrapper(localName = "implementacionMOResponse", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementacionMOResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double implementacionMO()
;

    @WebMethod(action = "urn:ImplementacionML")
    @RequestWrapper(localName = "implementacionML", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementacionML")
    @ResponseWrapper(localName = "implementacionMLResponse", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementacionMLResponse")
    public void implementacionML()
;

    @WebMethod(action = "urn:ImplementarSumar")
    @RequestWrapper(localName = "implementarSumar", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementarSumar")
    @ResponseWrapper(localName = "implementarSumarResponse", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementarSumarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double implementarSumar(

        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    );

    @WebMethod(action = "urn:ImplementacionUR")
    @RequestWrapper(localName = "implementacionUR", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementacionUR")
    @ResponseWrapper(localName = "implementacionURResponse", targetNamespace = "http://calculadora/", className = "wsCalculadora.ImplementacionURResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double implementacionUR()
;
}
